services:

  
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
    

  client-gateway:
    image: 'rocnail23/client-gateway:1.0.0'
    build: 
      context: ./gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./gateway/src:/usr/src/app/src
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222


  product-ms:
    image: 'rocnail23/product-ms:latest'
    build: 
      context: ./product-ms
      dockerfile: dockerfile.prod
      args:
        - DATABASE_URL=file:./dev.db
    volumes:
      - ./product-ms/src:/usr/src/app/src
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  
  # Orders MS
  order-ms:
    image: 'rocnail23/order-ms:latest'
    depends_on:
      - order-db
    build: 
      context: ./order-ms
      dockerfile: dockerfile.prod
      args:
        - DATABASE_URL=postgresql://postgres:123456@order-db:5432/ordersdb?schema=public
    volumes:
      - ./order-ms/src:/usr/src/app/src
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:123456@order-db:5432/ordersdb?schema=public



  # Orders DB
  order-db:
    image: 'rocnail23/order-db:latest'
    container_name: orders_database
    restart: always
    volumes:
      - ./order-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb

# ======================
# Payments Microservice
# ======================
  payment-ms:
    image: 'rocnail23/payment-ms:1.0.0'
    container_name: payment-ms
    build: 
      context: ./payment-ms
      dockerfile: dockerfile.prod
    volumes:
      - ./payment-ms/src:/usr/src/app/src
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      